@baseUrl = http://localhost:3000/api/v1
# @baseUrl = https://www.bancarios.news/api/v1
# @baseUrl =

### Get status
GET {{baseUrl}}/status

### List pending migrations
GET {{baseUrl}}/migrations

### Run pending migrations
POST {{baseUrl}}/migrations
